#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as bash,
#       ksh, or zsh, then to run this script, type that shell name before the
#       whole command line, like:
#
#           ksh Gradle start up script
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#           «${var#pattern}», «${var%pattern}»;
#         * compound commands having a return value;
#         * various built-in commands including `command`, `set`, and `trap`.
#
#   Important for patching:
#
#   (1) If you are using Gradle >= 7.0 to generate the wrapper files, you should use
#       the new locations and not need to patch them.
#
###############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a symlink
PRG="$0"
# Need this for daisy-chained symlinks.
while [ -h "$PRG" ] ; do
    ls -ld "$PRG"
    link=$( ls -ld "$PRG" | awk '{print $NF}' )
    case $link in                                                                 
      /*) PRG="$link" ;;
      *) PRG="$( dirname "$PRG" )/$link" ;;
    esac
done
SAVED="$( cd -P "$( dirname "$PRG" )" && pwd )"
APP_HOME="$SAVED"
cd "$APP_HOME" || exit

APP_NAME="Gradle"
APP_BASE_NAME=$( basename "$0" )

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                                                             
  CYGWIN* )         cygwin=true  ;;
  Darwin* )         darwin=true  ;;
  MSYS* | MINGW* )  msys=true    ;;
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/bin/java" ] ; then
        JAVACMD=$JAVA_HOME/jre/bin/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in                                                               
      max*)
        MAX_FD=$( expr $MAX_FD : 'max\(.*\)' ) ;;
    esac
    if [ "$MAX_FD" = maximum ] ; then
        MAX_FD=65535
    fi
    if [ -n "$MAX_FD" ] && [ "$MAX_FD" -gt 0 ] ; then
        ulimit -n $MAX_FD || warn "Could not set maximum file descriptor limit: $MAX_FD"
    fi
fi

# Escape application args
save () {
    for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/" ; done
    echo " "
}
APP_ARGS=$( save "$@" )
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
JAVACMD=$( save "$JAVACMD" )

# Now we can finally invoke the wrapper script.
exec "$JAVACMD" "${DEFAULT_JVM_OPTS[@]}" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$APP_ARGS"
